### ISSUE TITLE
Remove default 'gulp' prefix?

### ISSUE THREAD

**Issue by callumlocke** [simbo/auto-plug#2]
I think gulp users should be required to be explicit, i.e. `require('auto-plug')('gulp')`.

I get that defaults are convenient, but I think in this case it leans too far towards magic. Also, it's favoritism that feels counter to the purpose of auto-plug, ie. to be 'the' way to auto-require plugins for anything. I think it should stick to its guns and be completely agnostic.

**Comment by simbo** [comment]
Good point. Thanks for your suggestion.
Although i haven't thought about that yet, i totally understand your point. But i'm a bit in a struggle with myself because i like the whole "write less, do magic" thing and i use auto-plug mostly for gulp already in a lot of projects. But i agree and will probably change that with the next release (which will then be a major version bump to avoid breaking projects using the default 'gulp' value).

**Comment by callumlocke** [comment]
I like the magic thing in many cases too, but I think this case is different.

To make you feel better about changing it... I think (maybe counter-intuitively) gulp users will be more likely to switch over from gulp-load-plugins if you remove the default. Most people's first encounter with auto-plug will not be your readme; it will be seeing it used in a gulpfile in the wild. If they first see it as `require('auto-plug')()`, they will just think it's another gulp-load-plugins. But if they see `require('auto-plug')('gulp')`, they'll immediately see that it's an agnostic, multipurpose plugin loader, and they'll probably like the idea of that and use it in their own projects.

**Comment by simbo** [comment]
Done.
